### ISSUE TITLE
Check for `authClient ===null` is missing

### ISSUE THREAD

**Issue by ArjunQBTech** [ICP-hub/liftcash#33]
### Possible Fixes : 
- Add an additional check for the same inside the if condition before executing the statements inside it

![image](https://github.com/user-attachments/assets/39560aae-2e50-4e65-a65a-3a23d2584c33)

**Comment by rajnishQuadb** [comment]
Thanks for raising this issue!
It's been fixed now. Let me know if you encounter anything else!
